### PR TITLE
fix utmpx ifdef

### PR DESCRIPTION
**Pull request by christoph-zededa**
02e16ad95fb1f56ab004b01a10aab89f7103c55d did a copy-paste for utmpx, but forgot to change the ifdef appropriately

This fix also has been done in the alpine repo: https://github.com/alpinelinux/aports/blob/master/main/openssh/fix-utmp.patch#L31

### CODE REVIEW

**Comment by dkwo** [comment]
with 9.9p1, i also get https://github.com/void-linux/void-packages/pull/52297
```
usr/bin/ld: loginrec.o: in function `record_failed_login':
loginrec.c:(.text+0x116a): undefined reference to `construct_utmp'
```
is this part of the same issue?

**Comment by djmdjm** [comment]
> with 9.9p1, i also get [void-linux/void-packages#52297](https://github.com/void-linux/void-packages/pull/52297)
> 
> ```
> usr/bin/ld: loginrec.o: in function `record_failed_login':
> loginrec.c:(.text+0x116a): undefined reference to `construct_utmp'
> ```
> 
> is this part of the same issue?

Almost certainly not; that was probably caused by 671c440786a5a66216

**Comment by dkwo** [comment]
@djmdjm That was fixed in Void by this patch https://github.com/void-linux/void-packages/blob/master/srcpkgs/openssh/patches/musl-btmp.patch
We also carry a bunch of other patches, maybe this one https://github.com/void-linux/void-packages/blob/master/srcpkgs/openssh/patches/ssh-musl-gssapi.patch could be upstreamed too?

**Comment by djmdjm** [comment]
thanks, I just applied both of those

**Comment by djmdjm** [comment]
btw, I've pushed all these commits to the stable V_9_9 branch
