### PR TITLE
avoid deprecated ERR_load_crypto_strings API

### PR DESCRIPTION
**Pull request by vapier**
This function was deprecated in 1.1.0 which setting OpenSSL API compt to 0x10100000L disables the API.  Trying to build with OpenSSL 1.1.1w fails now with:
```
ssherr-libcrypto.c:39:2: error:
  call to undeclared function 'ERR_load_crypto_strings';
  ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
   39 |         ERR_load_crypto_strings();
      |         ^
```

From the [OpenSSL CHANGES file](https://github.com/openssl/openssl/blob/OpenSSL_1_1_1w/CHANGES#L2196-L2201):
> However, applications are strongly advised to compile their source files with `-DOPENSSL_API_COMPAT=0x10100000L`, which **hides the declarations of all interfaces deprecated in** 0.9.8, 1.0.0 or the **1.1.0 releases**.

Switch to the replacement API which is available in OpenSSL 1.1.1 (the oldest OpenSSH supports) and all current versions.

### CODE REVIEW

**Comment by ddekob15-boop** [comment]
شكراً

**Comment by ddekob15-boop** [comment]
Thanks

**Comment by djmdjm** [comment]
Thanks, committed as d9df26d7e93f76bc5b1c0cbd31cde0af00ccbbc0

**Comment by ddekob15-boop** [comment]
para agradecer

**Comment by ddekob15-boop** [comment]
to thank
